-- ============================================================
-- FOLLOW-UPS (call-backs, meetings, tasks) + due reminders
--
-- A follow-up is a dated to-do for one teammate, optionally tied to a
-- contact, a deal and the conversation it came from ("call him back
-- next Monday"). When `due_at` passes, `notify_due_follow_ups()` drops
-- an in-app notification for the assignee (type 'follow_up_due').
--
-- Visibility: agents/viewers see follow-ups assigned to (or created
-- by) them; admins and owners see the whole account.
--
-- Reminders are generated by `notify_due_follow_ups()`, which runs:
--   * every minute via pg_cron, when the extension is available, and
--   * from every open dashboard tab (client RPC), scoped to the caller,
--     so reminders still arrive if pg_cron can't be enabled.
--
-- Idempotent — safe to run multiple times.
-- ============================================================

CREATE TABLE IF NOT EXISTS follow_ups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  contact_id UUID REFERENCES contacts(id) ON DELETE CASCADE,
  deal_id UUID REFERENCES deals(id) ON DELETE CASCADE,
  conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
  type TEXT NOT NULL DEFAULT 'call'
    CHECK (type IN ('call', 'follow_up', 'meeting', 'task')),
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  notes TEXT,
  due_at TIMESTAMPTZ NOT NULL,
  -- auth.users id of the teammate who has to do it.
  assigned_to UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  completed_at TIMESTAMPTZ,
  -- Set once the due notification has been sent; cleared on reschedule.
  reminded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_follow_ups_account_due
  ON follow_ups(account_id, due_at);
CREATE INDEX IF NOT EXISTS idx_follow_ups_assignee_open
  ON follow_ups(assigned_to, due_at) WHERE completed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_follow_ups_pending_reminder
  ON follow_ups(due_at) WHERE completed_at IS NULL AND reminded_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_follow_ups_contact ON follow_ups(contact_id);
CREATE INDEX IF NOT EXISTS idx_follow_ups_deal ON follow_ups(deal_id);

-- ------------------------------------------------------------
-- Integrity trigger: linked rows and the assignee must belong to the
-- same account; rescheduling re-arms the reminder.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION follow_ups_before_write()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM profiles
    WHERE user_id = NEW.assigned_to AND account_id = NEW.account_id
  ) THEN
    RAISE EXCEPTION 'Assignee is not a member of this account';
  END IF;

  IF NEW.contact_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM contacts WHERE id = NEW.contact_id AND account_id = NEW.account_id
  ) THEN
    RAISE EXCEPTION 'Contact does not belong to this account';
  END IF;

  IF NEW.deal_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM deals WHERE id = NEW.deal_id AND account_id = NEW.account_id
  ) THEN
    RAISE EXCEPTION 'Deal does not belong to this account';
  END IF;

  IF NEW.conversation_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM conversations WHERE id = NEW.conversation_id AND account_id = NEW.account_id
  ) THEN
    RAISE EXCEPTION 'Conversation does not belong to this account';
  END IF;

  IF TG_OP = 'UPDATE' THEN
    NEW.updated_at := NOW();
    IF NEW.due_at IS DISTINCT FROM OLD.due_at
       OR NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
      NEW.reminded_at := NULL;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

ALTER FUNCTION follow_ups_before_write() OWNER TO postgres;

DROP TRIGGER IF EXISTS on_follow_ups_before_write ON follow_ups;
CREATE TRIGGER on_follow_ups_before_write
  BEFORE INSERT OR UPDATE ON follow_ups
  FOR EACH ROW EXECUTE FUNCTION follow_ups_before_write();

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------
ALTER TABLE follow_ups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS follow_ups_select ON follow_ups;
DROP POLICY IF EXISTS follow_ups_insert ON follow_ups;
DROP POLICY IF EXISTS follow_ups_update ON follow_ups;
DROP POLICY IF EXISTS follow_ups_delete ON follow_ups;

CREATE POLICY follow_ups_select ON follow_ups FOR SELECT USING (
  is_account_member(account_id, 'admin')
  OR (
    is_account_member(account_id)
    AND (assigned_to = auth.uid() OR created_by = auth.uid())
  )
);

CREATE POLICY follow_ups_insert ON follow_ups FOR INSERT WITH CHECK (
  is_account_member(account_id, 'agent')
  AND created_by = auth.uid()
);

CREATE POLICY follow_ups_update ON follow_ups FOR UPDATE USING (
  is_account_member(account_id, 'admin')
  OR (
    is_account_member(account_id, 'agent')
    AND (assigned_to = auth.uid() OR created_by = auth.uid())
  )
) WITH CHECK (is_account_member(account_id, 'agent'));

CREATE POLICY follow_ups_delete ON follow_ups FOR DELETE USING (
  is_account_member(account_id, 'admin')
  OR (
    is_account_member(account_id, 'agent')
    AND (assigned_to = auth.uid() OR created_by = auth.uid())
  )
);

-- ------------------------------------------------------------
-- Notifications: new 'follow_up_due' type + link back to the row.
-- ------------------------------------------------------------
ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS follow_up_id UUID REFERENCES follow_ups(id) ON DELETE CASCADE;

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('conversation_assigned', 'follow_up_due'));

-- ------------------------------------------------------------
-- notify_due_follow_ups() — turn due follow-ups into notifications.
--
-- Called with a user session (client RPC) it only processes the
-- caller's own follow-ups; called without one (pg_cron / service
-- role) it processes every account. Marking `reminded_at` inside the
-- same statement guarantees each follow-up notifies once even when
-- several tabs call this concurrently.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_due_follow_ups()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  WITH due AS (
    UPDATE follow_ups f
    SET reminded_at = NOW()
    WHERE f.completed_at IS NULL
      AND f.reminded_at IS NULL
      AND f.due_at <= NOW()
      AND (auth.uid() IS NULL OR f.assigned_to = auth.uid())
    RETURNING f.*
  ),
  inserted AS (
    INSERT INTO notifications (
      account_id, user_id, type, conversation_id, contact_id,
      follow_up_id, actor_user_id, title, body
    )
    SELECT
      d.account_id,
      d.assigned_to,
      'follow_up_due',
      COALESCE(
        d.conversation_id,
        (SELECT c.id FROM conversations c
          WHERE c.contact_id = d.contact_id AND c.account_id = d.account_id
          ORDER BY c.last_message_at DESC NULLS LAST
          LIMIT 1)
      ),
      d.contact_id,
      d.id,
      d.created_by,
      'Follow-up due: ' || d.title,
      CONCAT_WS(' · ',
        (SELECT COALESCE(NULLIF(ct.name, ''), ct.phone) FROM contacts ct WHERE ct.id = d.contact_id),
        (SELECT dl.title FROM deals dl WHERE dl.id = d.deal_id),
        NULLIF(d.notes, '')
      )
    FROM due d
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_count FROM inserted;

  RETURN v_count;
END;
$$;

ALTER FUNCTION notify_due_follow_ups() OWNER TO postgres;
REVOKE ALL ON FUNCTION notify_due_follow_ups() FROM PUBLIC;
REVOKE ALL ON FUNCTION notify_due_follow_ups() FROM anon;
GRANT EXECUTE ON FUNCTION notify_due_follow_ups() TO authenticated, service_role;

-- ------------------------------------------------------------
-- Schedule every minute with pg_cron when available. Failure here is
-- non-fatal: dashboard tabs call the function as a fallback.
-- ------------------------------------------------------------
DO $$
BEGIN
  BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_cron;
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pg_cron not available (%); reminders will run from open dashboard tabs only.', SQLERRM;
  END;

  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    BEGIN
      PERFORM cron.schedule(
        'wacrm-follow-up-reminders',
        '* * * * *',
        'SELECT public.notify_due_follow_ups()'
      );
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'Could not schedule follow-up reminders (%).', SQLERRM;
    END;
  END IF;
END $$;
